name: Cypress
on:
  push:
    branches:
      - main
      - release-*
  pull_request:
jobs:
  cypress-run:
    name: Test
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        browsers: [chrome] # [chrome, firefox] # deactivated firefox due to timeout issues
        node-version: [20.16]
    steps:
      - name: Set Action Environment Variables
        run: |
          echo "CYPRESS_RECORD_KEY=${{ secrets.CYPRESS_RECORD_KEY }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Checkout Source Files
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Set Chapter Environment Variables
        run: cp .env.example .env

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: ${{ env.CYPRESS_RECORD_KEY != 0 }}
          build: npm run build:coverage
          start: npm run start:ci
          wait-on: 'http://localhost:3000, http://localhost:5000/graphql'
          browser: ${{ matrix.browsers }}

      - name: Print Cypress coverage report
        run: npm run cypress:coverage:report

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: cypress-screenshots
          path: cypress/screenshots
