name: Deploy to Uberspace Test
on:
  # run workflow manually from Actions tab
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Uberspace Demo
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avrh --delete
          path: ./
          remote_path: /var/www/virtual/${{ vars.UBERSPACE_SSH_USER }}/html
          remote_host: ${{ vars.UBERSPACE_SSH_HOST }}
          remote_user: ${{ vars.UBERSPACE_SSH_USER }}
          remote_key: ${{ secrets.UBERSPACE_SSH_PRIVATE_KEY }}
