name: Deploy to Uberspace test environment
on:
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Uberspace test environment
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avrh --delete
          path: ./
          remote_path: /var/www/virtual/${{ vars.UBERSPACE_SSH_USER }}/chapter2-node-app
          remote_host: ${{ vars.UBERSPACE_SSH_HOST }}
          remote_user: ${{ vars.UBERSPACE_SSH_USER }}
          remote_key: ${{ secrets.UBERSPACE_SSH_PRIVATE_KEY }}

      - name: Build on Uberspace test environment
        if: ${{ success() }}
        uses: appleboy/ssh-action@v1.0.3
        env:
          NODE_ENV: 'NODE_ENV=production'
        with:
          host: ${{ vars.UBERSPACE_SSH_HOST }}
          username: ${{ vars.UBERSPACE_SSH_USER }}
          key: ${{ secrets.UBERSPACE_SSH_PRIVATE_KEY }}
          envs: NODE_ENV
          script: |
            echo "### Set $NODE_ENV"
            cd chapter2-node-app
            echo "### install and build server"
            npm ci -w=server --ignore-scripts
            npm run build -w=server
            echo "### install and build server finished"
            echo "### install and build client"
            npm ci -w=client --ignore-scripts
            npm run build -w=client
            echo "### install and build client finished"
