name: Update copyright year(s) in license file

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 1 1 *' # 03:00 on day-of-month 1 in January

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: |
            README.md
            LICENSE
          commitTitle: 'docs: update copyright years'
          prTitle: 'docs: update copyright years'
          prBody: It's that time of the year, let's update the license
          labels: Documentation
