name: Update GitHub pages
on:
  push:
    branches: [main]
jobs:
  publish:
    if: github.repository == 'freeCodeCamp/chapter'
    name: Publish to GitHub pages
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [20.x]
    services:
      postgres:
        # For now schema spy doesn't get on with postgres:14
        image: postgres:16
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: chapter
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm ci
      - name: Create the schema
        env:
          DB_PORT: 5432
        run: 'npm run prisma migrate reset -- --force --skip-generate --skip-seed'
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          ref: gh-pages
      - name: Run SchemaSpy
        run: |
          docker run --user="root" --network="host" -v "$PWD:/output" schemaspy/schemaspy -vizjs -t pgsql -db chapter -host localhost -port 5432 -u postgres -p password

      - name: Publish to GitHub pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "docs: update database documentation"
          git push
